### ISSUE TITLE
Can`t fetch response - is empty in

### ISSUE THREAD

**Issue by 512banque** [smi2/phpClickHouse#126]
After trying to insert massive csv files, I get this kind of answer:

```
Fatal error: Uncaught ClickHouseDB\Exception\TransportException: Can`t fetch response - is empty in /tmp/vendor/smi2/phpclickhouse/src/Transport/CurlerRequest.php:619
Stack trace:
#0 /tmp/vendor/smi2/phpclickhouse/src/Statement.php(106): ClickHouseDB\Transport\CurlerRequest->response()
#1 /tmp/vendor/smi2/phpclickhouse/src/Statement.php(183): ClickHouseDB\Statement->response()
#2 /tmp/vendor/smi2/phpclickhouse/src/Client.php(601): ClickHouseDB\Statement->isError()
#3 /tmp/vendor/smi2/phpclickhouse/src/Client.php(556): ClickHouseDB\Client->insertBatchFiles('xxxxx...', Array, Array, 'TabSeparated')
#4 /tmp/php/clickhouseimport.php(62): ClickHouseDB\Client->insertBatchTSVFiles('xxxx...', Array, Array)
#5 {main}
  thrown in /tmp/vendor/smi2/phpclickhouse/src/Transport/CurlerRequest.php on line 619
```

**Comment by isublimity** [comment]
Sorry long answer - if problem exists, please give me full example like this https://github.com/smi2/phpClickHouse/blob/master/example/exam12_array.php
