### ISSUE TITLE
Неправильная подстановка bindings

### ISSUE THREAD

**Issue by z80maniac** [smi2/phpClickHouse#47]
Вот такой код:
```php
$db = new ClickHouseDB\Client([
    "host" => "127.0.0.1",
    "port" => 8123,
    "username" => "default",
    "password" => ""
]);

$db->select("SELECT :a, :b", [
    "a" => ":b",
    "b" => ":a"
])->rows();
```

выдаёт ошибку:
```
PHP Fatal error:  Uncaught ClickHouseDB\DatabaseException: Syntax error: failed at position 10: :a'', ':a' FORMAT JSON. Expected one of: identifier, alias, AS, token, AND, OR, BETWEEN, IS, LIKE, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, QuestionMark, ORDER BY, SETTINGS, INTO OUTFILE, FORMAT, FROM, PREWHERE, WHERE, GROUP BY, WITH, HAVING, LIMIT, UNION ALL
IN:SELECT '':a'', ':a' FORMAT JSON in /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php:162
Stack trace:
#0 /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php(196): ClickHouseDB\Statement->error()
#1 /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php(210): ClickHouseDB\Statement->check()
#2 /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php(459): ClickHouseDB\Statement->init()
#3 /home/user/test/phpcl_bug/test.php(15): ClickHouseDB\Statement->rows()
#4 {main}
  thrown in /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php on line 162
```

Другой пример:
```php
$db->select("SELECT :a, :a2", [
    "a" => "x",
    "a2" => "x"
])->rows();
```
```
PHP Fatal error:  Uncaught ClickHouseDB\DatabaseException: Syntax error: failed at position 16: 2 FORMAT JSON. Expected one of: identifier, alias, AS, token, AND, OR, BETWEEN, IS, LIKE, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, QuestionMark, ORDER BY, SETTINGS, INTO OUTFILE, FORMAT, FROM, PREWHERE, WHERE, GROUP BY, WITH, HAVING, LIMIT, UNION ALL
IN:SELECT 'x', 'x'2 FORMAT JSON in /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php:162
Stack trace:
#0 /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php(196): ClickHouseDB\Statement->error()
#1 /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php(210): ClickHouseDB\Statement->check()
#2 /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php(459): ClickHouseDB\Statement->init()
#3 /home/user/test/phpcl_bug/test.php(22): ClickHouseDB\Statement->rows()
#4 {main}
  thrown in /home/user/test/phpcl_bug/phpClickHouse/src/Statement.php on line 162
```

**Comment by isublimity** [comment]
У вас последняя версия?
я попробую поправить их поведение, но вообще `bindings + conditions is deprecated`

**Comment by z80maniac** [comment]
> У вас последняя версия?

На момент написания была последняя из Git.

> bindings + conditions is deprecated

Хм. Не видел нигде, что bindings стали deprecated. А как тогда переписать, например, первый запрос? Есть какая-то альтернатива bindings?

**Comment by z80maniac** [comment]
Второй пример теперь работает. Первый - по-прежнему выдаёт ошибку.

**Comment by isublimity** [comment]
Первый пример он спорный))) 

bind внутри bind

я использую для этого конструкцию `{key}`

А как вы видите это должно работать?

**Comment by z80maniac** [comment]
Как мне кажется, значения массива должны просто подставляться именно как конечные значения и не парситься дальше. Допустим, какая-то форма в приложении запрашивает два поля "a" и "b". Юзер вводит туда строки ":b" и ":a" соответственно. Это вызовет вышеописанную ошибку в БД.

Т.е. первый пример должен, по логике, выдавать то же самое, что и запрос `SELECT ':b', ':a';` (т.е. просто строки, которые были во входных данных).

**Comment by isublimity** [comment]
Согласен убрал на `:` двойной прогон - перезалил 1.1.1 сборку

```
$keys=[
            'A'=>'{B}',
            'B'=>':C',
            'C'=>123,
            'Z'=>[':C',':B',':C']
        ];
        $this->assertEquals(
            "123 ':C',':B',':C' FORMAT JSON",
            $this->client->selectAsync('{A} :Z', $keys)->sql()
        );
```

**Comment by z80maniac** [comment]
> перезалил 1.1.1 сборку

Через composer всё равно ставится старая версия 1.1.1 (без коммитов "DoubleBind").

**Comment by isublimity** [comment]
Собрал 1.1.2

**Comment by z80maniac** [comment]
Ок, теперь, кажись, всё. Спасибо!
